### ISSUE TITLE
Error in Make Install

### ISSUE THREAD

**Issue by dinhan92** [duydo/elasticsearch-analysis-vietnamese#103]
Chào bạn, khi mình cài Step đầu tiên qua Ubuntu LTS, khi chạy câu lệnh make install thì lỗi như sau:
: not foundld_java.sh: 2: ../java/build_java.sh:
../java/build_java.sh: 36: ../java/build_java.sh: Syntax error: end of file unexpected (expecting "then")
CMakeFiles/compile_java.dir/build.make:60: recipe for target 'coccoc-tokenizer.jar' failed
make[2]: *** [coccoc-tokenizer.jar] Error 2
CMakeFiles/Makefile2:215: recipe for target 'CMakeFiles/compile_java.dir/all' failed
make[1]: *** [CMakeFiles/compile_java.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Hy vọng bạn giúp mình với ^^

**Comment by duydo** [comment]
@dinhan92 Bạn nhớ install JDK trước rồi follow kỹ từng câu lệnh trong hướng dẫn cài đặt nha.
