### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by dvdieu** [duydo/elasticsearch-analysis-vietnamese#105]
----------  S U M M A R Y ------------

Command Line: -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT --add-opens=java.base/java.io=ALL-UNNAMED -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/tmp/elasticsearch-9645801560421129381 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=536870912 -Des.path.home=/opt/bitnami/elasticsearch -Des.path.conf=/opt/bitnami/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -Des.bundled_jdk=true org.elasticsearch.bootstrap.Elasticsearch -p /opt/bitnami/elasticsearch/tmp/elasticsearch.pid

Host: AMD EPYC 7542 32-Core Processor, 16 cores, 62G, Debian GNU/Linux 10 (buster)
Time: Sun Jun 27 18:57:29 2021 UTC elapsed time: 90.434870 seconds (0d 0h 1m 30s)

---------------  T H R E A D  ---------------

Current thread (0x00007fcf8c102800):  JavaThread "elasticsearch[elasticsearch-node1][search][T#19]" daemon [_thread_in_native, id=855, stack(0x00007fcfca7fc000,0x00007fcfca8fd000)]

Stack: [0x00007fcfca7fc000,0x00007fcfca8fd000],  sp=0x00007fcfca8f8ec8,  free space=1011k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libc.so.6+0x15c74a]

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.coccoc.Tokenizer.initialize(Ljava/lang/String;)I+0
j  com.coccoc.Tokenizer.<init>(Ljava/lang/String;)V+6
j  org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.lambda$new$0(Lorg/elasticsearch/analysis/VietnameseConfig;)Lcom/coccoc/Tokenizer;+8
j  org.apache.lucene.analysis.vi.VietnameseTokenizerImpl$$Lambda$5078.run()Ljava/lang/Object;+4
v  ~StubRoutines::call_stub
J 613  java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.11 (0 bytes) @ 0x00007fd080233a0f [0x00007fd0802339c0+0x000000000000004f]
j  org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.<init>(Lorg/elasticsearch/analysis/VietnameseConfig;Ljava/io/Reader;)V+73
j  org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(Lorg/elasticsearch/analysis/VietnameseConfig;)V+71
j  org.elasticsearch.index.analysis.VietnameseTokenizerFactory.create()Lorg/apache/lucene/analysis/Tokenizer;+8
j  org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(Ljava/lang/String;)Lorg/apache/lucene/analysis/Analyzer$TokenStreamComponents;+4
j  org.apache.lucene.analysis.AnalyzerWrapper.createComponents(Ljava/lang/String;)Lorg/apache/lucene/analysis/Analyzer$TokenStreamComponents;+8
J 9559 c2 org.apache.lucene.analysis.Analyzer.tokenStream(Ljava/lang/String;Ljava/lang/String;)Lorg/apache/lucene/analysis/TokenStream; (89 bytes) @ 0x00007fd080b12d38 [0x00007fd080b12b20+0x0000000000000218]
j  org.elasticsearch.index.search.MatchQueryParser$MatchQueryBuilder.createQuery(Ljava/lang/String;Ljava/lang/String;Lorg/elasticsearch/index/search/MatchQueryParser$Type;Lorg/apache/lucene/search/BooleanClause$Occur;I)Lorg/apache/lucene/search/Query;+6
j  org.elasticsearch.index.search.MatchQueryParser$MatchQueryBuilder.createFieldQuery(Lorg/apache/lucene/analysis/Analyzer;Lorg/apache/lucene/search/BooleanClause$Occur;Ljava/lang/String;Ljava/lang/String;ZI)Lorg/apache/lucene/search/Query;+53
j  org.apache.lucene.util.QueryBuilder.createBooleanQuery(Ljava/lang/String;Ljava/lang/String;Lorg/apache/lucene/search/BooleanClause$Occur;)Lorg/apache/lucene/search/Query;+34
j  org.elasticsearch.index.search.MatchQueryParser.parseInternal(Lorg/elasticsearch/index/search/MatchQueryParser$Type;Ljava/lang/String;Lorg/elasticsearch/index/search/MatchQueryParser$MatchQueryBuilder;Ljava/lang/Object;)Lorg/apache/lucene/search/Query;+58
j  org.elasticsearch.index.search.MatchQueryParser.parse(Lorg/elasticsearch/index/search/MatchQueryParser$Type;Ljava/lang/String;Ljava/lang/Object;)Lorg/apache/lucene/search/Query;+249
j  org.elasticsearch.index.query.MatchQueryBuilder.doToQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+189
j  org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+2
j  org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(Lorg/elasticsearch/index/query/SearchExecutionContext;Lorg/apache/lucene/search/BooleanQuery$Builder;Ljava/util/List;Lorg/apache/lucene/search/BooleanClause$Occur;)V+33
j  org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+17
j  org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+2
j  org.elasticsearch.index.query.SearchExecutionContext.lambda$toQuery$3(Lorg/elasticsearch/index/query/QueryBuilder;)Lorg/apache/lucene/search/Query;+2
j  org.elasticsearch.index.query.SearchExecutionContext$$Lambda$5287.apply(Ljava/lang/Object;)Ljava/lang/Object;+8
j  org.elasticsearch.index.query.SearchExecutionContext.toQuery(Lorg/elasticsearch/index/query/QueryBuilder;Lorg/elasticsearch/common/CheckedFunction;)Lorg/elasticsearch/index/query/ParsedQuery;+20
j  org.elasticsearch.index.query.SearchExecutionContext.toQuery(Lorg/elasticsearch/index/query/QueryBuilder;)Lorg/elasticsearch/index/query/ParsedQuery;+8
j  org.elasticsearch.search.SearchService.parseSource(Lorg/elasticsearch/search/DefaultSearchContext;Lorg/elasticsearch/search/builder/SearchSourceBuilder;Z)V+67
j  org.elasticsearch.search.SearchService.createContext(Lorg/elasticsearch/search/internal/ReaderContext;Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;Z)Lorg/elasticsearch/search/internal/SearchContext;+40
j  org.elasticsearch.search.SearchService.executeQueryPhase(Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+22
j  org.elasticsearch.search.SearchService.access$500(Lorg/elasticsearch/search/SearchService;Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+3
j  org.elasticsearch.search.SearchService$2.lambda$onResponse$0(Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+6
j  org.elasticsearch.search.SearchService$2$$Lambda$5277.get()Ljava/lang/Object;+12
j  org.elasticsearch.search.SearchService$$Lambda$5278.get()Ljava/lang/Object;+4
j  org.elasticsearch.action.ActionRunnable.lambda$supply$0(Lorg/elasticsearch/common/CheckedSupplier;Lorg/elasticsearch/action/ActionListener;)V+2
j  org.elasticsearch.action.ActionRunnable$$Lambda$5279.accept(Ljava/lang/Object;)V+8
j  org.elasticsearch.action.ActionRunnable$2.doRun()V+8
J 11069 c1 org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (32 bytes) @ 0x00007fd0791bbca4 [0x00007fd0791bbba0+0x0000000000000104]
j  org.elasticsearch.common.util.concurrent.TimedRunnable.doRun()V+11
j  org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun()V+24
J 11069 c1 org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (32 bytes) @ 0x00007fd0791bbca4 [0x00007fd0791bbba0+0x0000000000000104]
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@11.0.11
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@11.0.11
j  java.lang.Thread.run()V+11 java.base@11.0.11
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

**Comment by dvdieu** [comment]
> ---------- S U M M A R Y ------------
> 
> Command Line: -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT --add-opens=java.base/java.io=ALL-UNNAMED -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -Djava.io.tmpdir=/tmp/elasticsearch-9645801560421129381 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=data -XX:ErrorFile=logs/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Xms1024m -Xmx1024m -XX:MaxDirectMemorySize=536870912 -Des.path.home=/opt/bitnami/elasticsearch -Des.path.conf=/opt/bitnami/elasticsearch/config -Des.distribution.flavor=default -Des.distribution.type=tar -Des.bundled_jdk=true org.elasticsearch.bootstrap.Elasticsearch -p /opt/bitnami/elasticsearch/tmp/elasticsearch.pid
> 
> Host: AMD EPYC 7542 32-Core Processor, 16 cores, 62G, Debian GNU/Linux 10 (buster)
> Time: Sun Jun 27 18:57:29 2021 UTC elapsed time: 90.434870 seconds (0d 0h 1m 30s)
> 
> --------------- T H R E A D ---------------
> 
> Current thread (0x00007fcf8c102800): JavaThread "elasticsearch[elasticsearch-node1][search][T#19]" daemon [_thread_in_native, id=855, stack(0x00007fcfca7fc000,0x00007fcfca8fd000)]
> 
> Stack: [0x00007fcfca7fc000,0x00007fcfca8fd000], sp=0x00007fcfca8f8ec8, free space=1011k
> Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
> C [libc.so.6+0x15c74a]
> 
> Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
> j com.coccoc.Tokenizer.initialize(Ljava/lang/String;)I+0
> j com.coccoc.Tokenizer.(Ljava/lang/String;)V+6
> j org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.lambda$new$0(Lorg/elasticsearch/analysis/VietnameseConfig;)Lcom/coccoc/Tokenizer;+8
> j org.apache.lucene.analysis.vi.VietnameseTokenizerImpl$$Lambda$5078.run()Ljava/lang/Object;+4
> v ~StubRoutines::call_stub
> J 613 java.security.AccessController.doPrivileged(Ljava/security/PrivilegedAction;)Ljava/lang/Object; java.base@11.0.11 (0 bytes) @ 0x00007fd080233a0f [0x00007fd0802339c0+0x000000000000004f]
> j org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.(Lorg/elasticsearch/analysis/VietnameseConfig;Ljava/io/Reader;)V+73
> j org.apache.lucene.analysis.vi.VietnameseTokenizer.(Lorg/elasticsearch/analysis/VietnameseConfig;)V+71
> j org.elasticsearch.index.analysis.VietnameseTokenizerFactory.create()Lorg/apache/lucene/analysis/Tokenizer;+8
> j org.elasticsearch.index.analysis.CustomAnalyzer.createComponents(Ljava/lang/String;)Lorg/apache/lucene/analysis/Analyzer$TokenStreamComponents;+4
> j org.apache.lucene.analysis.AnalyzerWrapper.createComponents(Ljava/lang/String;)Lorg/apache/lucene/analysis/Analyzer$TokenStreamComponents;+8
> J 9559 c2 org.apache.lucene.analysis.Analyzer.tokenStream(Ljava/lang/String;Ljava/lang/String;)Lorg/apache/lucene/analysis/TokenStream; (89 bytes) @ 0x00007fd080b12d38 [0x00007fd080b12b20+0x0000000000000218]
> j org.elasticsearch.index.search.MatchQueryParser$MatchQueryBuilder.createQuery(Ljava/lang/String;Ljava/lang/String;Lorg/elasticsearch/index/search/MatchQueryParser$Type;Lorg/apache/lucene/search/BooleanClause$Occur;I)Lorg/apache/lucene/search/Query;+6
> j org.elasticsearch.index.search.MatchQueryParser$MatchQueryBuilder.createFieldQuery(Lorg/apache/lucene/analysis/Analyzer;Lorg/apache/lucene/search/BooleanClause$Occur;Ljava/lang/String;Ljava/lang/String;ZI)Lorg/apache/lucene/search/Query;+53
> j org.apache.lucene.util.QueryBuilder.createBooleanQuery(Ljava/lang/String;Ljava/lang/String;Lorg/apache/lucene/search/BooleanClause$Occur;)Lorg/apache/lucene/search/Query;+34
> j org.elasticsearch.index.search.MatchQueryParser.parseInternal(Lorg/elasticsearch/index/search/MatchQueryParser$Type;Ljava/lang/String;Lorg/elasticsearch/index/search/MatchQueryParser$MatchQueryBuilder;Ljava/lang/Object;)Lorg/apache/lucene/search/Query;+58
> j org.elasticsearch.index.search.MatchQueryParser.parse(Lorg/elasticsearch/index/search/MatchQueryParser$Type;Ljava/lang/String;Ljava/lang/Object;)Lorg/apache/lucene/search/Query;+249
> j org.elasticsearch.index.query.MatchQueryBuilder.doToQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+189
> j org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+2
> j org.elasticsearch.index.query.BoolQueryBuilder.addBooleanClauses(Lorg/elasticsearch/index/query/SearchExecutionContext;Lorg/apache/lucene/search/BooleanQuery$Builder;Ljava/util/List;Lorg/apache/lucene/search/BooleanClause$Occur;)V+33
> j org.elasticsearch.index.query.BoolQueryBuilder.doToQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+17
> j org.elasticsearch.index.query.AbstractQueryBuilder.toQuery(Lorg/elasticsearch/index/query/SearchExecutionContext;)Lorg/apache/lucene/search/Query;+2
> j org.elasticsearch.index.query.SearchExecutionContext.lambda$toQuery$3(Lorg/elasticsearch/index/query/QueryBuilder;)Lorg/apache/lucene/search/Query;+2
> j org.elasticsearch.index.query.SearchExecutionContext$$Lambda$5287.apply(Ljava/lang/Object;)Ljava/lang/Object;+8
> j org.elasticsearch.index.query.SearchExecutionContext.toQuery(Lorg/elasticsearch/index/query/QueryBuilder;Lorg/elasticsearch/common/CheckedFunction;)Lorg/elasticsearch/index/query/ParsedQuery;+20
> j org.elasticsearch.index.query.SearchExecutionContext.toQuery(Lorg/elasticsearch/index/query/QueryBuilder;)Lorg/elasticsearch/index/query/ParsedQuery;+8
> j org.elasticsearch.search.SearchService.parseSource(Lorg/elasticsearch/search/DefaultSearchContext;Lorg/elasticsearch/search/builder/SearchSourceBuilder;Z)V+67
> j org.elasticsearch.search.SearchService.createContext(Lorg/elasticsearch/search/internal/ReaderContext;Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;Z)Lorg/elasticsearch/search/internal/SearchContext;+40
> j org.elasticsearch.search.SearchService.executeQueryPhase(Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+22
> j org.elasticsearch.search.SearchService.access$500(Lorg/elasticsearch/search/SearchService;Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+3
> j org.elasticsearch.search.SearchService$2.lambda$onResponse$0(Lorg/elasticsearch/search/internal/ShardSearchRequest;Lorg/elasticsearch/action/search/SearchShardTask;)Lorg/elasticsearch/search/SearchPhaseResult;+6
> j org.elasticsearch.search.SearchService$2$$Lambda$5277.get()Ljava/lang/Object;+12
> j org.elasticsearch.search.SearchService$$Lambda$5278.get()Ljava/lang/Object;+4
> j org.elasticsearch.action.ActionRunnable.lambda$supply$0(Lorg/elasticsearch/common/CheckedSupplier;Lorg/elasticsearch/action/ActionListener;)V+2
> j org.elasticsearch.action.ActionRunnable$$Lambda$5279.accept(Ljava/lang/Object;)V+8
> j org.elasticsearch.action.ActionRunnable$2.doRun()V+8
> J 11069 c1 org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (32 bytes) @ 0x00007fd0791bbca4 [0x00007fd0791bbba0+0x0000000000000104]
> j org.elasticsearch.common.util.concurrent.TimedRunnable.doRun()V+11
> j org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun()V+24
> J 11069 c1 org.elasticsearch.common.util.concurrent.AbstractRunnable.run()V (32 bytes) @ 0x00007fd0791bbca4 [0x00007fd0791bbba0+0x0000000000000104]
> j java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+92 java.base@11.0.11
> j java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@11.0.11
> j java.lang.Thread.run()V+11 java.base@11.0.11
> v ~StubRoutines::call_stub
> 
> siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000000

services:
  elasticsearch-node1:
    image: docker.io/dieudv/elasticsearch-vietnamese-tokenizier-coccoc
    restart: "unless-stopped"
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node1
      - ELASTICSEARCH_HEAP_SIZE=4g
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'data01:/bitnami'
    networks:
      - flick-network

  elasticsearch-node2:
    image: docker.io/dieudv/elasticsearch-vietnamese-tokenizier-coccoc
    restart: "unless-stopped"
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node2
      - ELASTICSEARCH_HEAP_SIZE=4g
    volumes:
      - 'data02:/bitnami'
    networks:
      - flick-network

  elasticsearch-node3:
    image: docker.io/dieudv/elasticsearch-vietnamese-tokenizier-coccoc
    restart: "unless-stopped"
    environment:
      - ELASTICSEARCH_CLUSTER_NAME=elasticsearch-cluster
      - ELASTICSEARCH_CLUSTER_HOSTS=elasticsearch-node1,elasticsearch-node2,elasticsearch-node3
      - ELASTICSEARCH_NODE_NAME=elasticsearch-node3
      - ELASTICSEARCH_HEAP_SIZE=4g
    volumes:
      - 'data03:/bitnami'
    networks:
      - flick-network
      
volumes:
  data01:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /data/elasticsearch/1
  data02:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /data/elasticsearch/2
  data03:
    driver: local
    driver_opts:
      type: local
      o: bind
      device: /data/elasticsearch/3

networks:
  flick-network:
    driver: bridge

**Comment by duydo** [comment]
Bug này được fix trong release mới nhất rồi nha @dvdieu
