### ISSUE TITLE
Error when "mvn elasticsearch-analysis-vietnamese-7.13.0.zip" ??

### ISSUE THREAD

**Issue by BinhMinhs10** [duydo/elasticsearch-analysis-vietnamese#107]
![Screenshot from 2021-07-02 10-15-26](https://user-images.githubusercontent.com/22696815/124215568-74cc9b00-db1e-11eb-8b67-7fe67fe020e5.png)

**Comment by mbb-engineering** [comment]
Có thông tin bên này rồi nè bạn: https://github.com/duydo/elasticsearch-analysis-vietnamese/issues/102
