### ISSUE TITLE
Does vi_analyzer still have lowercase?

### ISSUE THREAD

**Issue by trungtv1207** [duydo/elasticsearch-analysis-vietnamese#109]
In branch vntokenizer, vi_analyzer have lowercase, vi_tokenizer and stop.
But I dont see lowercase listed in this branch (coccoc-tokenizer).
Please let me know if this branch still have lowercase.

In addition, can this plugin convert vietnamese to non-accent vietnamese (example: â --> a)?
Thanks

**Comment by duydo** [comment]
@trungtv1207 It already have lowercase by default in coccoc-tokenizer. 

In addition, can this plugin convert vietnamese to non-accent vietnamese (example: â --> a)? -> No. You can use `icu analysis` plugin for your purpose.
