### ISSUE TITLE
Do you plan a 2.1.1 version?

### ISSUE THREAD

**Issue by dripp1** [duydo/elasticsearch-analysis-vietnamese#11]
The plugin version 2.1.0 is not compatible with ES 2.1.1

Thanks

**Comment by nguyenchiencong** [comment]
:+1:

**Comment by duydo** [comment]
Yes, next few days :-)

**Comment by duydo** [comment]
@dripp1 @nguyenchiencong I've just updated the plugin to support ES 2.1.1.

**Comment by dripp1** [comment]
Thank you!

**Comment by nguyenchiencong** [comment]
you rock! :cake:
