### ISSUE TITLE
Uncompleted package !!!

### ISSUE THREAD

**Issue by thusinh1969** [duydo/elasticsearch-analysis-vietnamese#110]
1) Package không cài được vì thiếu dependency, không chạy được
2) Không có guide đầy đủ để hoàn tất chạy được
3) Nên XÓA đi đừng public thế này kỳ lắm

Steve

**Comment by duydo** [comment]
@thusinh1969 Bình luận không có tính xây dựng, tôi đóng bình luận :-)
