### ISSUE TITLE
Vấn đề về Get All Document Analysis

### ISSUE THREAD

**Issue by ninhtruong** [duydo/elasticsearch-analysis-vietnamese#112]
Cho em hỏi là em đã put nhiều tài liệu lên để phân tích và giờ em muốn get tất cả gói đã phân tích về hoặc nhiều gói theo 1 điều kiện nào đó. Em đã research khá nhiều nhưng chưa giải quyết được vấn đề. Mong anh chị em có thể hỗ trợ em về phần này. Em cảm ơn nhiều

**Comment by duydo** [comment]
@ninhtruong Em xem thêm docs về Search DSL nha
