### ISSUE TITLE
Highlighting Issue (v. 2.2.0)

### ISSUE THREAD

**Issue by dripp1** [duydo/elasticsearch-analysis-vietnamese#12]
Thank you for the plugin, but I have an issue with highlighting of matched terms. I use version 2.2.0.
When I run the following query:
```
{
  "query": {
    "bool": {
      "should": {
        "multi_match": {
          "query": "chữ",
          "fields": [
            "message",
            "user"
          ],
          "analyzer": "default_search"
        }
      }
    }
  },
  "highlight": {
    "pre_tags": [
      "<b>"
    ],
    "post_tags": [
      "</b>"
    ],
    "fragment_size": 0,
    "number_of_fragments": 0,
    "require_field_match": false,
    "fields": {
      "message": {},
      "user": {}
    }
  }
}
```
I get the following result, where the highlighting offsets are wrong and they wrap the wrong words:
```
{
	"took" : 14,
	"timed_out" : false,
	"_shards" : {
		"total" : 200,
		"successful" : 200,
		"failed" : 0
	},
	"hits" : {
		"total" : 1,
		"max_score" : 0.030578919,
		"hits" : [{
				"_index" : "fts-vietnamese",
				"_type" : "Document",
				"_id" : "AVKcb6Xy0-uCokJzleqC",
				"_score" : 0.030578919,
				"_source" : {
					"streamId" : 1,
					"language" : "vietnamese",
					"message" : "Có một vấn đề là khi sent text messages dùng tiếng Việt hoặc email qua người khác, chữ tiếng Việt bị mất dấu hoặc mất chữ. Chẳng hạn như chữ “ôm” thì thành",
					"doc_id" : "VietnameseWords"
				},
				"highlight" : {
					"message" : [
						"Có một vấn đề là khi sent text messages dùng tiếng Việt hoặc email <b>qua</b> người khác, chữ tiếng V<b>iệt</b> bị mất dấu h<b>oặc</b> mất chữ. Chẳng hạn như chữ “ôm” thì thành"
					]
				}
			}
		]
	}
}
```
Can you please advise whether this is a bug that you can fix or something that I can configure in my code.
Thank you!

**Comment by duydo** [comment]
I'll have a look at it. Thanks for your reports.

**Comment by dripp1** [comment]
Thank you. Also - if you are at it - perhaps you can make a version compatible with Elastic Search 2.2.0 as the current version can only work with 2.1.1 and I get error:

ERROR: Plugin [elasticsearch-analysis-vietnamese] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]

Thanks!

**Comment by duydo** [comment]
@dripp1 The plugin now supports ES 2.2.0

**Comment by nguyenchiencong** [comment]
:+1:

**Comment by dripp1** [comment]
Thank you!

**Comment by dripp1** [comment]
The plugin indeed now works on ES 2.2.0 and indexing is done, but the above highlighting issue still exists. It would be great if you could fix this, as it makes this important functionality unusable.
Thank you.

**Comment by dripp1** [comment]
Hi @duydo - is there a chance that you will have time soon to look at this issue? 
The plugin is really not of much use to us as long as this issue exists. Thanks in advance!

**Comment by duydo** [comment]
@dripp1 I have not found any reason behinds this, it seems that it comes from the Elasticsearch itself. I suspect the highlight parser does not work with Vietnamese characters, I will contact with some guys at Elastic this week.

**Comment by dripp1** [comment]
Thank you very much, it will be great if a solution is found.

**Comment by dripp1** [comment]
Hi @duydo -  did the Elastic people provide a solution to this?

**Comment by dripp1** [comment]
@duydo please see an answer from ES support for this question at [https://discuss.elastic.co/t/highlighting-offset-issue-with-vietnamese/50421](url) - seems like they think that the problem is in the analyzer/tokenizer that produces wrong offsets.

**Comment by duydo** [comment]
I'm working on it, hope it can be fixed soon. Thanks @dripp1

**Comment by dripp1** [comment]
Awesome!

**Comment by dripp1** [comment]
@duydo - Any news on this?

**Comment by dripp1** [comment]
@duydo - any chance that you may have time to fix this issue? Without that - the plugin is pretty useless...

**Comment by duydo** [comment]
@dripp1 The issue has been fixed.

**Comment by dripp1** [comment]
Thank you
