### ISSUE TITLE
Bị lỗi khi cài đặt trên MacOS

### ISSUE THREAD

**Issue by lttin0912** [duydo/elasticsearch-analysis-vietnamese#127]
Khi em chạy lệnh mvn package thì bị lỗi này:

[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   VietnameseAnalysisIntegrationTests>ESTestCase.<clinit>:244 » Runtime unable to...
[ERROR]   VietnameseAnalysisTests.org.elasticsearch.index.analysis.VietnameseAnalysisTests » NoClassDefFound
[INFO] 
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

Anh hướng dẫn giúp em với ạ

**Comment by vankhoa229** [comment]
> @lttin0912 Em build với ES version mấy vậy?

Em đang build với 7.17.1 bị lỗi như trên luôn ạ.
