### ISSUE TITLE
Support for ES 8.3?

### ISSUE THREAD

**Issue by mofolo** [duydo/elasticsearch-analysis-vietnamese#128]
Hi thank you for your plugin
Is there any support for Elastic Search 8.3?

**Comment by duydo** [comment]
@mofolo Thanks for being interested in the plugin. 
I'm working on upgrading it to Elasticsearch 8.x.

**Comment by mofolo** [comment]
Great work, thank you.

**Comment by mofolo** [comment]
I managed to build your changes on v8.3.3 by skipping the tests - unfortunately the plugin didn't seem to work.

**Comment by duydo** [comment]
> I managed to build your changes on v8.3.3 by skipping the tests - unfortunately the plugin didn't seem to work.

[This branch](https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/feature/upgrade-to-es-8.x) contains the code for v8.3.3, you can try.

**Comment by mofolo** [comment]
Hey @duydo - Question, does the plugin need to have the tokenizer on the same machine for it to work or is the tokenizer wrapped into the JAR plugin itself?
Is there anyway to use this plugin on Elastic that's been created using Elastic Cloud?

**Comment by duydo** [comment]
@mofolo 
> Hey @duydo - Question, does the plugin need to have the tokenizer on the same machine for it to work or is the tokenizer wrapped into the JAR plugin itself? 

Yes, you need to have the C++ tokenizer on the same machine running Elasticsearch.

> Is there anyway to use this plugin on Elastic that's been created using Elastic Cloud?
It seems that Elastic Cloud does not support install custom plugins using native lib via JNI.

**Comment by mofolo** [comment]
Yes you're right, the Cloud version doesn't allow us to load custom binaries onto the machine running Elastic either.

Would it be viable (although not as effective) to fork a version of the repo that utilises the vnTokenizer
(https://github.com/duydo/vn-nlp-libraries) and package everything into the JAR?
