### ISSUE TITLE
Can it be used with elasticsearch 2.2?

### ISSUE THREAD

**Issue by dpinol** [duydo/elasticsearch-analysis-vietnamese#13]
If I try
`bin/plugin  install  https://dl.dropboxusercontent.com/u/1598491/elasticsearch-analysis-vietnamese-0.2.1.1.zip
`
I get:
`ERROR: Plugin [elasticsearch-analysis-vietnamese] is incompatible with Elasticsearch [2.2.0]. Was designed for version [2.1.1]`

thanks!

**Comment by duydo** [comment]
Thank @dpinol for using the plugin, I will provide a build for ES 2.2.0.

**Comment by duydo** [comment]
@dpinol The plugin now supports ES 2.2.0
