### ISSUE TITLE
8.7.0 error

### ISSUE THREAD

**Issue by 2547409617** [duydo/elasticsearch-analysis-vietnamese#142]
It run in docker

Error openning file, alphabetic
{"@timestamp":"2023-07-10T07:26:54.223Z", "log.level":"ERROR", "message":"fatal error in thread [elasticsearch[bf7d3a67956b][clusterApplierService#updateTask][T#1]], exiting", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"elasticsearch[bf7d3a67956b][clusterApplierService#updateTask][T#1]","log.logger":"org.elasticsearch.bootstrap.ElasticsearchUncaughtExceptionHandler","elasticsearch.cluster.uuid":"bfW1H15ATiuvSfFnp0yvVg","elasticsearch.node.id":"blN9KOSeSEmQzpsDEfuSXA","elasticsearch.node.name":"bf7d3a67956b","elasticsearch.cluster.name":"docker-cluster","error.type":"java.lang.ExceptionInInitializerError","error.stack_trace":"java.lang.ExceptionInInitializerError\n\tat com.coccoc.Tokenizer.getInstance(Tokenizer.java:59)\n\tat org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.lambda$new$0(VietnameseTokenizerImpl.java:54)\n\tat java.base/java.security.AccessController.doPrivileged(AccessController.java:318)\n\tat org.apache.lucene.analysis.vi.VietnameseTokenizerImpl.<init>(VietnameseTokenizerImpl.java:53)\n\tat org.apache.lucene.analysis.vi.VietnameseTokenizer.<init>(VietnameseTokenizer.java:45)\n\tat org.apache.lucene.analysis.vi.VietnameseAnalyzer.createComponents(VietnameseAnalyzer.java:88)\n\tat org.apache.lucene.core@9.5.0/org.apache.lucene.analysis.AnalyzerWrapper.createComponents(AnalyzerWrapper.java:120)\n\tat org.apache.lucene.core@9.5.0/org.apache.lucene.analysis.Analyzer.tokenStream(Analyzer.java:193)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.index.analysis.AnalysisRegistry.checkVersions(AnalysisRegistry.java:747)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.index.analysis.AnalysisRegistry.produceAnalyzer(AnalysisRegistry.java:710)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:602)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.index.analysis.AnalysisRegistry.build(AnalysisRegistry.java:210)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.index.IndexModule.newIndexService(IndexModule.java:515)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.indices.IndicesService.createIndexService(IndicesService.java:731)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:624)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.indices.IndicesService.createIndex(IndicesService.java:175)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.indices.cluster.IndicesClusterStateService.createIndicesAndUpdateShards(IndicesClusterStateService.java:476)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.indices.cluster.IndicesClusterStateService.applyClusterState(IndicesClusterStateService.java:226)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:538)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:524)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:497)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:428)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:154)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:891)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:257)\n\tat org.elasticsearch.server@8.7.0/org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:223)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)\n\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)\n\tat java.base/java.lang.Thread.run(Thread.java:1589)\nCaused by: java.lang.RuntimeException: Cannot initialize Tokenizer: /usr/local/share/tokenizer/dicts\n\tat com.coccoc.Tokenizer.<init>(Tokenizer.java:65)\n\tat com.coccoc.Tokenizer.<init>(Tokenizer.java:12)\n\tat com.coccoc.Tokenizer$Loader.get(Tokenizer.java:53)\n\tat com.coccoc.Tokenizer$Loader.<clinit>(Tokenizer.java:47)\n\t... 29 more\n"}

**Comment by duydo** [comment]
Thanks @2547409617 for reporting bugs. It seems that there is a bug in the tokenizer while loading the dictionary, I'll work on that.

**Comment by duydo** [comment]
@2547409617 I couldn't re-produce the bugs, I tested on master branch and it still works.

**Comment by duydo** [comment]
Close this issue due to no feedback from @2547409617

**Comment by vukhacbiet** [comment]
Mình cũng gặp lỗi tương tự khi build docker image

![Screenshot 2023-09-17 at 12 00 24](https://github.com/duydo/elasticsearch-analysis-vietnamese/assets/43400653/cc6a9f93-b6cc-4ab0-99a4-c24a851c6e99)

Error:
![Screenshot 2023-09-17 at 12 01 49](https://github.com/duydo/elasticsearch-analysis-vietnamese/assets/43400653/c8f94860-a5da-4ad6-a9c5-76fc9c03c562)
