### ISSUE TITLE
8.7.0 error

### ISSUE THREAD

**Issue by meofiscoding** [duydo/elasticsearch-analysis-vietnamese#144]
**[Updated]**:
I had install and build your github project from source code, after running the command :
`sudo ln -sf /usr/local/lib/libcoccoc_tokenizer_jni.* /usr/lib/`

I encountered the following error message: `ln: /usr/lib//libcoccoc_tokenizer_jni.dylib: Operation not permitted`. This error suggests that the System Integrity Protection (SIP) might be active on my macOS system, preventing the creation of the symbolic link. Should I proceed by disabling SIP to resolve this issue?

---
I got this error after install your plugin:
`"error.type":"java.lang.UnsatisfiedLinkError","error.message":"no coccoc_tokenizer_jni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"
`

And then i had Appending /usr/local/lib into environment variable LD_LIBRARY_PATH by running this in terminal:
`export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH`

But when im making symbolic link by running :
`ln -sf /usr/local/lib/libcoccoc_tokenizer_jni.so /usr/lib/libcoccoc_tokenizer_jni.so`
then i got `ln: /usr/lib/libcoccoc_tokenizer_jni.so: Operation not permitted`

So im trying to copy to usr/lib by running :
`cp /usr/local/lib/libcoccoc_tokenizer_jni.so /usr/lib`
And then i got `cp: /usr/local/lib/libcoccoc_tokenizer_jni.so: No such file or directory`

**Comment by meofiscoding** [comment]
I had notice that `make install` command just install `libcoccoc_tokenizer_jni.dylib` under `/usr/local/lib/` and there are no `libcoccoc_tokenizer_jni.so` file. i think you should update your readme file

**Comment by duydo** [comment]
> I had notice that `make install` command just install `libcoccoc_tokenizer_jni.dylib` under `/usr/local/lib/` and there are no `libcoccoc_tokenizer_jni.so` file. I think you should update your readme file. @duydo
The extension  `.dylib` is dynamic lib for MacOS and the `*.so` is for Linux, it depends on operating system you have built but I'll update the README for more clear.  Thanks @meofiscoding  for trying the plugin.
