### ISSUE TITLE
Hỗ trợ 8.12?

### ISSUE THREAD

**Issue by QuanTran91** [duydo/elasticsearch-analysis-vietnamese#148]
Anh Duy ơi cho em hỏi là khi nào anh có kế hoạch hỗ trợ ES 8.12 không? Hay mình có thể dùng plugin này cho 8.12 được không? 
Cảm ơn anh.

**Comment by duydo** [comment]
Nếu em cần gấp thì có thể sửa lại version trong file POM để build thử nhé em. Trong quá trình build có vấn đề gì anh sẽ hỗ trợ.
