### ISSUE TITLE
Upgrade new version elasticsearch-analysis-vietnamese for ES 2.3.1

### ISSUE THREAD

**Issue by huyhoang1990** [duydo/elasticsearch-analysis-vietnamese#15]
Now, im using ES version 2.3.1, And i want to try your plugin to improve search.

When do you upgrade your plugin compatible with other version of ES ?

Thanks

**Comment by mkchen89** [comment]
Topic này có vẻ hẩm hiu quá, ko thấy author vào ý kiến nhể :3

**Comment by duydo** [comment]
Mấy nay mình bận quá chưa build version mới được, vài hôm nữa mình sẽ build.

**Comment by huyhoang1990** [comment]
Hi Anh Duy!
   Khi nào anh rảnh cho em gặp anh uống cafe hỏi han được không anh :D . 
   Nếu anh tiện thì anh add skype của em với ạ :   huyhoang01011990

**Comment by duydo** [comment]
@huyhoang1990 Có gì gởi trao đổi với anh qua skype duy.doquoc hoặc email doquocduy@gmail.com  em nhé.

**Comment by duydo** [comment]
@huyhoang1990 Mình đã build cho các version 2.3.0 -> 2.3.5

**Comment by huyhoang1990** [comment]
Cảm ơn Anh ạ !

2016-08-23 6:39 GMT+07:00 Duy Do <notifications@github.com>:
