### ISSUE TITLE
Hỏi về cài đặt thư viện

### ISSUE THREAD

**Issue by kien-vu-uet** [duydo/elasticsearch-analysis-vietnamese#150]
Em chào anh ạ! Em có một vài thắc mắc mong anh giải đáp.
1. Hiện tại em đã dựng 1 elasticsearch server (ver 8.12.1), việc cài đặt thêm lib có cần thiết phải setup lại từ đầu không và lib có hỗ trợ phiên bản cao hơn không (ver 8.12)? 
2. Em muốn sử dụng các bộ tokenizer khác (VncoreNLP) có được không?

**Comment by duydo** [comment]
1. Cài plugin không phải setup ES từ đầu nha em. Hiện tại plugin chưa hỗ trợ 8.12, nếu em quen với Java và có thời gian em clone về rồi build cho 8.12 thử nhé.
2. Sử dụng bộ tokenzier nào cũng được, em xem class VietnameseTokenizer để hiểu cách tích hợp.
