### ISSUE TITLE
tokenizer not found

### ISSUE THREAD

**Issue by vuchiencong** [duydo/elasticsearch-analysis-vietnamese#151]
a duy oi co em hỏi chút ạ, em cài plugun dc gết rồi ạ, test cococ_tokenizer cũng oke hết r, es cũng chạy dc r, nhưng khi e tạo index và put setting cho n thì n báo v ạ  
Elasticsearch exception [type=illegal_argument_exception, reason=Custom Analyzer [my_vi_analyzer] failed to find tokenizer under name [vi_tokenizer]] 
không biết e thiếu đoặn nào k ạ, hay đổi tên đâu k ạ

**Comment by vuchiencong** [comment]
{
    "error": {
        "root_cause": [
            {
                "type": "illegal_argument_exception",
                "reason": "Custom Analyzer [my_vi_analyzer] failed to find tokenizer under name [vi_tokenizer]"
            }
        ],
        "type": "illegal_argument_exception",
        "reason": "Custom Analyzer [my_vi_analyzer] failed to find tokenizer under name [vi_tokenizer]"
    },
    "status": 400
}

**Comment by duydo** [comment]
Em chạy cái này xem ra kết quả như thế nào: 
```curl -k http://elastic:changeme@localhost:9200/_analyze -H 'Content-Type: application/json' -d '
{
  "analyzer": "vi_analyzer",
  "text": "Cộng hòa Xã hội chủ nghĩa Việt Nam"
}'
```
Tiện thể cho anh xem settings khi em tạo index nhé.

**Comment by vuchiencong** [comment]
em cài được rồi anh ạ, vấn đề do depOps bên em cài es nhiều node, e cài trên các node rồi restart lại là được rồi anh ạ
