### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by hieuthanhpro** [duydo/elasticsearch-analysis-vietnamese#153]
anh Duy ơi cho em hỏi ví dụ e đang dùng là 
GET /_analyze
{
  "tokenizer": "vi_tokenizer",
  "text" : "thơ lục bát!"
}
và kết quả được 
{
  "tokens": [
    {
      "token": "thơ",
      "start_offset": 0,
      "end_offset": 3,
      "type": "<WORD>",
      "position": 0
    },
    {
      "token": "lục bát",
      "start_offset": 4,
      "end_offset": 11,
      "type": "<WORD>",
      "position": 1
    }
  ]
}
và em muốn tách thành 3 token là:  "thơ" ,"lục" ,"bát"
 thì em phải làm như nào ạ. Em xin cảm ơn anh ạ

**Comment by duydo** [comment]
Nếu em muốn tách từ theo space thì dùng default analyzer đi em, không phải dùng đến plugin này.

**Comment by hieuthanhpro** [comment]
Dạ em cảm ơn anh ạ
