### ISSUE TITLE
Cài thư viện vào plugin elasticsearch

### ISSUE THREAD

**Issue by 19longdt** [duydo/elasticsearch-analysis-vietnamese#155]
Em chào anh, khi build dự án của anh ra file jar, em thực hiện cài plugin ở elasticsearch thì bị lỗi
![image](https://github.com/user-attachments/assets/51519ae8-47a8-4553-83c5-29f12fb62314)

em có dùng cả bản release 8.7.0 của anh nhưng đều ra lỗi này ạ
![image](https://github.com/user-attachments/assets/88d556a8-a8b5-4fc2-acb6-e1e8f55832c3)

em ko rõ là mình bị thiếu bước nào, mong anh trả lời ạ.
Em cảm ơn Anh!

**Comment by 19longdt** [comment]
em đoán do thiếu file plugin-descriptor.properties

nhưng em có cài bản release 8.7.0, nguyên cả file zip cũng lỗi này

**Comment by duydo** [comment]
> em đoán do thiếu file plugin-descriptor.properties
> 
> nhưng em có cài bản release 8.7.0, nguyên cả file zip cũng lỗi này

Theo thông báo thì đúng là thiếu file descriptors. Em post logs khi build plugin anh xem thử nhé.

**Comment by 19longdt** [comment]
![image](https://github.com/user-attachments/assets/8a64922a-93f8-441a-9f37-c56fb3967b7c)

có vẻ như đang bị thiếu file stable-plugin-descriptor.properties anh ạ!

**Comment by duydo** [comment]
Không có phản hồi từ @19longdt từ 20/09 đến giờ, anh đóng issue này nhé.
