### ISSUE TITLE
Hỏi về kiểm tra bản ghi đã tồn tại

### ISSUE THREAD

**Issue by hatienkma** [duydo/elasticsearch-analysis-vietnamese#18]
Chào mọi người,

Mình mới nghiên cứu về ES. Phiên bản của mình dùng mới nhất hiện tại.

Mình dùng elasticsearch-php để index và get dữ liệu.

Mình muốn kiểm tra 1 bản ghi trước khi chèn vào, ví dụ như chưa có thì chèn, có rồi bỏ qua.

Mong mọi người hỗ trợ.

**Comment by duydo** [comment]
Cài này em qua bên [group](https://www.facebook.com/groups/elasticsearchvn/) thảo luận nhé, cái này để mở issue cho cái plugin tiếng Việt thôi.
