### ISSUE TITLE
analyzer [vi_analyzer] not found for field [content]

### ISSUE THREAD

**Issue by hohieukn** [duydo/elasticsearch-analysis-vietnamese#19]
Hi duydo,
I have problem with this plugin. 
I am using:
elasticsearch-analysis-vietnamese-2.4.0.zip
and 
elasticsearch_2.4

FOR VI_TOKENIZER
it ok when using for analyzer
#####################
POST _analyze
{
  "tokenizer": "vi_tokenizer",
  "text": "giá cả thế nào hả bạn"
}
RESULT
{
   "tokens": [
      {
         "token": "giá cả",
         "start_offset": 0,
         "end_offset": 6,
         "type": "word",
         "position": 0
      },
      {
         "token": "thế nào",
         "start_offset": 7,
         "end_offset": 14,
         "type": "word",
         "position": 1
      },
      {
         "token": "hả",
         "start_offset": 15,
         "end_offset": 17,
         "type": "word",
         "position": 2
      },
      {
         "token": "bạn",
         "start_offset": 18,
         "end_offset": 21,
         "type": "word",
         "position": 3
      }
   ]
}
#######################
but when i am using this for build customize analyzer this CAN'T find VI_TOKENIZER

PUT resource_message
{
   "settings": {
      "analysis": {
         "analyzer": {
            "vi_customize_analyzer": {
               "type": "custom",
               "tokenizer": "vi_tokenizer"
            }
         }
      }
   }
}
RESULT IS:
{
   "error": {
      "root_cause": [
         {
            "type": "remote_transport_exception",
            "reason": "[Air-Walker][10.240.0.2:9300][indices:admin/create]"
         }
      ],
      "type": "illegal_argument_exception",
      "reason": "Custom Analyzer [vi_customize_analyzer] failed to find tokenizer under name [vi_tokenizer]"
   },
   "status": 400
}
######################################

FOR VI_ANALYZER
i am continue to using VI_ANALYZER. It good for analyzer request 
POST _analyze
{
  "analyzer": "vi_analyzer",
  "text": "giá cả thế nào hả bạn"
}
RESULT 
{
   "tokens": [
      {
         "token": "giá cả",
         "start_offset": 0,
         "end_offset": 6,
         "type": "word",
         "position": 0
      },
      {
         "token": "thế nào",
         "start_offset": 7,
         "end_offset": 14,
         "type": "word",
         "position": 1
      },
      {
         "token": "hả",
         "start_offset": 15,
         "end_offset": 17,
         "type": "word",
         "position": 2
      },
      {
         "token": "bạn",
         "start_offset": 18,
         "end_offset": 21,
         "type": "word",
         "position": 3
      }
   ]
}

but when i'm using this for mapping it fail
PUT resource_message
{
   "mappings": {
      "data": {
         "properties": {
            "content": {
               "type": "string",
               "analyzer": "vi_analyzer"
            }
         }
      }
   }
}
RESULT 
{
   "error": {
      "root_cause": [
         {
            "type": "mapper_parsing_exception",
            "reason": "analyzer [vi_analyzer] not found for field [content]"
         }
      ],
      "type": "mapper_parsing_exception",
      "reason": "Failed to parse mapping [data]: analyzer [vi_analyzer] not found for field [content]",
      "caused_by": {
         "type": "mapper_parsing_exception",
         "reason": "analyzer [vi_analyzer] not found for field [content]"
      }
   },
   "status": 400
}

I don't know what step i wrong. Can you help me ? :(

**Comment by thanhthai3010** [comment]
I am running the same query with you:
curl -XGET 'localhost:9200/_analyze?pretty' -H 'Content-Type: application/json' -d' {"tokenizer": "vi_tokenizer", "text": "giá cả thế nào hả bạn" } '

But unfortunate, I got the message: 
{
  "error" : {
    "root_cause" : [
      {
        "type" : "remote_transport_exception",
        "reason" : "[My First Node][127.0.0.1:9300][indices:admin/analyze[s]]"
      }
    ],
    "type" : "illegal_argument_exception",
    "reason" : "failed to find global tokenizer under [vi_tokenizer]"
  },
  "status" : 400
}
Could you please help me?

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
