### ISSUE TITLE
Elasticsearch 5.0

### ISSUE THREAD

**Issue by maitruong** [duydo/elasticsearch-analysis-vietnamese#20]
Hi a.Duy Do,
I've got this issue when installing your plugin into Elasticsearch 5.0 
Exception in thread "main" java.net.UnknownHostException: usr
Please help me to release a new version plugin which is compatible with Elasticsearch 5.
Thanks,
Mai Truong

**Comment by duydo** [comment]
Thanks for being interested in the plugin. I'm working on it.

**Comment by amelkikh** [comment]
Dear @duydo , a big request to you to implement support ASAP. Thank you

**Comment by duydo** [comment]
@maitruong @amelkikh The plugin has been upgraded to Elasticsearch 5.2.1.

**Comment by ndeitch** [comment]
Hi @duydo,

I'm upgrading a plugin of es2 to es5 in my job. 

Could you please, indicate some doc where I could learn how to. On elastic.co I couldn't find.

Thanks in advance!

**Comment by duydo** [comment]
@ndeitch I'm working on creating doc for the plugin, will ping you later.

**Comment by ndeitch** [comment]
@duydo,

I take another look on elastic docs, and found this [link](https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_plugins.html) that combined with your commit helped me a lot!

Thx!

**Comment by duydo** [comment]
@ndeitch Great to hear that. Thank you for using the plugin :-)
