### ISSUE TITLE
Plugin version for ES 2.4.4 

### ISSUE THREAD

**Issue by amelkikh** [duydo/elasticsearch-analysis-vietnamese#21]
Dear @duydo, could you help me to create plugin for ES 2.4.4 because it will allow me to complete my task. My request is due to the fact that I also use your plug-in in conjunction with another, but now I can not upgrade ES to version 5.
Thanks in advance

**Comment by duydo** [comment]
@amelkikh I will provide this version next week.

**Comment by khoimt** [comment]
Hi I built this follow guideline, you can try this

https://github.com/khoimt/elasticsearch-analysis-vietnamese/releases/download/2.4.4/elasticsearch-analysis-vietnamese-2.4.4.zip
