### ISSUE TITLE
More capitalization inconsistencies

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#30]
[I've got a number of issues, which I'm going to file separately, based on grouping related symptoms, but some of them may be related. I think a number of them may be related to matching patterns without good boundary detection.]

Below are some more examples (as in issue #26) of strings that differ only by case but are tokenized differently.
```
a1b2c3 => a 1 b 2 c 3
1a2b3c => 1 a 2 b 3 c

A1B2C3 => a1 b2 c3
1A2B3C => 1 a2 b3 c

aa1bbb24cccc369 => aa 1 bbb 24 cccc 369
AA1BBB24CCCC369 => AA1 BBB2 4 CCCC3 69

a_b => a b
A_b => A_ b
a_ => a
A_ => a_

1000x1000 => 1000 x 1000
1000X1000 => 1000 x1 000

X.Jones => x.j ones
X.jones => x jones
x.Jones => x jones
x.jones => x jones

X.Y.Jones => x.y.j ones
X.Y.jones => x.y jones
X.y.jones => x y jones

XX.YY.JJones => xx.yy.jjones
```

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
