### ISSUE TITLE
Number errors and inconsistencies

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#31]
1) Integers followed by a close paren, and then any character but space or return will make the paren part of the number token.
```
(10) => 10
(10), => 10)
(10)e => 10)  e
```
but:
```
(10.2) => 10.2
(10.2), => 10.2
```

2) Periods after numbers before spaces and tabs are not stripped:
```
10.\n10.\t10. 10. => 10   10.   10.   10
```
but:
```
2.10.\n2.10.\t2.10. 2.10. => 2.10   2.10   2.10   2.10
```

3) Period after number is inconsistently stripped:
```
10. => 10
10._ => 10.
10., => 10.
10.. => 10.
```

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
