### ISSUE TITLE
Contextual inconsistencies

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#32]
Seemingly unrelated characters around a token can sometimes change how it is parsed in unexpected ways.

1) Dash-connected-words are split differently depending on other words and punctuation:
```
xxx-yyy-zzz => xxx-yyy-zzz
w xxx-yyy-zzz => w + xxx + yyy-zzz
```
but:
```
. xxx-yyy-zzz => xxx-yyy-zzz
w. xxx-yyy-zzz => w + xxx-yyy-zzz
w, xxx-yyy-zzz => w + xxx-yyy-zzz
w- xxx-yyy-zzz => w + xxx-yyy-zzz
```
Any of these characters can come after the letter and preserve the dashed-connected-words: ```.  + - ; : ( ) , % ! ?```

2) Tabs are treated differently depending on what's around them:
```
x\ty => x\ty
```
but:
```
x\ty z => z + y + z
z x\ty => z + x + y
```

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
