### ISSUE TITLE
Many patterns need better word boundaries

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#33]
1) Slashes: In general slashes and dashes are treated unexpectedly based on how date-like or fraction-like they look in inappropriate contexts. Parsing of dates is fine, but not everything that looks like a date is, and MM/DD/YYYY format is not parsed. Parsing fractions is fine, too, but both dates and fractions should have proper word boundaries around them:
```
15/11/1910 => 15/11/1910
11/15/1910 => 11/15 + 1910
10/10/10 => 10/10/10
10/30/10 => 10/30 + 10
10/10/10/10/10/10 => 10/10/10 + 10/10/10
10/10/10/10/40/10 => 10/10/10 + 10/40 + 10
```

2) Dashes: Again, parsing dates is fine, though not everything that looks like a data is, and that causes inconsistencies. MM-DD-YYYY is not matched. Better word boundary detection would make more sense.

```
15-11-1910 => 15-11-1910
11-15-1910 => 11-15 + -1910
10-10-10 => 10-10-10
10-30-10 => 10-30 + -10
10-10-10-10-10-10 => 10-10-10 + -10 + -10 + -10
10-40-10-10-10-10 => 10-40 + -10 + -10 + -10 + -10
10-000-10-10-10-10 => 10-00 + 0 + -10 + -10 + -10 + -10

0-915826-22-4 => 0 + -915826 + -22 + -4
2-915826-22-4 => 2-9158 + 26-2 + 2-4

x-1y => x -1 y
```

3) URL domain matching is too aggressive: Domain matching doesn't limit itself to word boundaries, and so can break up tokens oddly, especially when there are accented characters:

```
Daily.ngày -> Daily.ng + ày
aaa.eee.iii -> aaa.eee.iii
aáa.eee.iii -> aáa + eee.iii
aaa.eée.iii -> aaa.e + ée + iii
aaa.eee.iíi -> aaa.eee.i + íi
```

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
