### ISSUE TITLE
Suggestion: better handle combining diacritics

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#34]
Combining characters (incluing diacritics and other characters in non-Latin scripts) cause tokens to split. Some examples from various scripts:

* ضَمَّة — Arabic
* বাংলা — Bengali
* Михаи́л — Cyrillic + combining acute
* दिल्ली — Devanagari
* ಅಕ್ಷರಮಾಲೆ — Kannada
* áa - Latin + combining acute (vs áa with precomposed character)
* ଓଡ଼ିଆ — Oriya
* தமிழ் — Tamil
* తెలుగు — Telugu
* อักษรไทย —Thai
* g͡b — International Phonetic Alphabet

**Comment by duydo** [comment]
I close this issue, it will be fixed in new tokenizer #37
