### ISSUE TITLE
Suggestion: Don't index whitespace and punctuation

### ISSUE THREAD

**Issue by Trey314159** [duydo/elasticsearch-analysis-vietnamese#35]
These whitespace and zero-width characters get indexed, but probably shouldn't be:

* no break space U+00A0
* en space U+2002
* em space U+2003
* three-per-em space U+2004
* four-per-em space U+2005
* six-per-em space U+2006
* figure space U+2007
* punctuation space U+2008
* thin space U+2009
* hair space U+200A
* zero width space U+200B
* zero width non-joiner U+200C
* zero width joiner U+200D
* left-to-right mark U+200E
* right-to-left mark U+200F
* narrow no-break-space U+202F
* medium mathematical space U+205F
* zero width no-break space U+FEFF

These punctuation characters get indexed, too, but probably don't need to be:

* §
* «
* ·
* »
* ‐ (hyphen U+2010, not -, which is "hyphen-minus")
* – (en dash)
* — (em dash)
* •
* …
* ′ (prime)
* ″ (double prime)
* ※
* 、
* 。
* 《
* 》
* 「
* 」
* （ (fullwidth paren)
* ） (fullwidth paren)
* ． (fullwidth period)
* ： (fullwidth colon)

**Comment by duydo** [comment]
I close this issue, it will be implemented in new tokenizer #37
