### ISSUE TITLE
Implement new tokenizer

### ISSUE THREAD

**Issue by duydo** [duydo/elasticsearch-analysis-vietnamese#37]
The original tokenizer has many issues Trey Jones has reported recently, I decide to implement a new version from scratch to solve those issues. This implementation is based on this paper https://www.researchgate.net/publication/29616221_A_Hybrid_Approach_to_Word_Segmentation_of_Vietnamese_Texts

**Comment by hoangpq** [comment]
Awesome, waiting for new releases :)

**Comment by telosma** [comment]
Awesome

**Comment by davesag** [comment]
What is the status of this ticket now?

**Comment by duydo** [comment]
@davesag 
> What is the status of this ticket now?
It is still in progress...but slow, I've just been so busy lately with my startup.

**Comment by kienvht** [comment]
Cảm ơn anh @duydo . Chúc anh ngày càng mạnh khỏe. Em cũng mong đợi bản release mới của anh.

**Comment by xiaoyuan0821** [comment]
Hi @duydo I'm trying to use this plugin on the production env, is this plugin production ready? Will it cause ES process crush in some scenario?

**Comment by duydo** [comment]
> Hi @duydo I'm trying to use this plugin on the production env, is this plugin production ready? Will it cause ES process crush in some scenario?

@xiaoyuan0821 There are some companies have been used the plugin in the production environment, I haven't received any crash report relates to it.

**Comment by duydo** [comment]
I've just released new version of the plugin with new C++ tokenizer library from CocCoc team. Thanks for your patience :-)

**Comment by duydo** [comment]
cc: @hoangpq @davesag @xiaoyuan0821 @telosma @kienvht
