### ISSUE TITLE
MapperParsingException

### ISSUE THREAD

**Issue by lfiaschi** [duydo/elasticsearch-analysis-vietnamese#4]
Hi,
I am trying to use the plugin however I did not manage to make it work.

After installation from binary source it seems to correctly load:
```
[2014-12-16 11:17:05,552][INFO ][node                     ] [elasticsearch] version[1.3.4], pid[3794], build[a70f3cc/2014-09-30T09:07:17Z]
[2014-12-16 11:17:05,553][INFO ][node                     ] [elasticsearch] initializing ...
[2014-12-16 11:17:05,577][INFO ][plugins                  ] [elasticsearch] loaded [marvel, jdbc-1.3.4.4-d2e33c3, analysis-vietnamese], sites [marvel]
```

However when I try to set a custom in the mapping of a new index as:
```
"keyword_account": {"fields": {"raw": {"index": "not_analyzed", "type": "string"}, 
"en": {"type": "string", "analyzer": "my_english"}, 
"th": {"type": "string", "analyzer": "thai"}, 
"splitted": {"type": "string", "analyzer": "my_analyzer"}, 
"id": {"type": "string", "analyzer": "indonesian"}, 
"vn": {"type": "string", "analyzer": "vi_analyzer"}
}, 
"type": "string"}
```

I get the following response:

```
 u'MapperParsingException[Analyzer [vi_analyzer] not found for field [vn]]
```

any clue?

**Comment by icovn** [comment]
After I install I run above curl command and I get this:
{"error":"ElasticsearchIllegalArgumentException[text is missing]","status":400}
Please explain this problem to me!

**Comment by dripp1** [comment]
Do you have a version compatible with ElasticSearch 1.6?

**Comment by duydo** [comment]
Hi @dripp1
Sorry for late reply. I've just released the version 1.6, you can download it here https://dl.dropboxusercontent.com/u/1598491/elasticsearch-analysis-vietnamese-0.1.6.zip

**Comment by dripp1** [comment]
Thank you!

**Comment by phamquick** [comment]
Em chào anh @duydo , plugin này của anh dường như không hỗ trợ tìm kiếm tiếng Việt không dấu. Em đã có thử qua  hunspell token filter nhưng vẫn không được ạ. Anh có thể hướng dẫn cho em giải pháp nào tìm kiếm tiếng Việt không dấu bằng Elasticsearch được không ạ?
Xin trân thành cảm ơn anh.

**Comment by duydo** [comment]
@icovn try this one:
```sh
curl http://localhost:9200/_analyze?analyzer=vi_analyzer -d 'công nghệ thông tin Việt Nam'
```
Result:
```
{
   "tokens": [
      {
         "token": "công nghệ thông tin",
         "start_offset": 2,
         "end_offset": 21,
         "type": "word",
         "position": 3
      },
      {
         "token": "việt nam",
         "start_offset": 21,
         "end_offset": 29,
         "type": "name2",
         "position": 6
      }
   ]
}
```
