### ISSUE TITLE
Error Code 500 crash internally

### ISSUE THREAD

**Issue by KingWu** [duydo/elasticsearch-analysis-vietnamese#40]
Dataset include a field with empty string, which seem to make it crash internally.

logstash         | [2017-09-28T13:13:39,840][INFO ][logstash.outputs.elasticsearch] Retrying individual bulk actions that failed or were rejected by the previous bulk request. {:count=>1}
logstash         | [2017-09-28T13:13:43,799][INFO ][logstash.outputs.elasticsearch] retrying failed action with response code: 500 ({"type"=>"string_index_out_of_bounds_exception", "reason"=>"String index out of range: 3"})

**Comment by duydo** [comment]
Thanks for your report. This is known issue, I've been working on it.
