### ISSUE TITLE
lỗi khi build mvn package trong window

### ISSUE THREAD

**Issue by huynhtran1509** [duydo/elasticsearch-analysis-vietnamese#41]
em chạy lệnh đến lẹnh 
cd elasticsearch-analysis-vietnamese
mvn package
thì bị lỗi sau:
[ERROR] Failed to execute goal com.carrotsearch.randomizedtesting:junit4-maven-plugin:2.3.3:junit4 (unit-tests) on project elasticsearch-analysis-vietnamese: There were test failures: 2 suites, 1 test, 1 suite-level error, 1 error [seed: 2073BF2290744A13]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

nếu e bỏ qua bước này và làm 2 cách như sau mà vẫn không tích hợp được ạ:
cách 1: tiếp tục thực hiện trong cmd:
C:\elasticsearch-5.4.1\bin\elasticsearch-plugin install C:\elasticsearch-analysis-vietnamese-5.4.1.zip 
file .zip download: https://github.com/duydo/elasticsearch-analysis-vietnamese/releases  (file chứa nhiều file java)
thì lỗi ERROR: Unknown plugin C:\elasticsearch-analysis-vietnamese-5.4.1.zip
cách 2: giải nén elasticsearch-analysis-vietnamese-5.4.1.zip (file chứa nhiều file java) ra được thư mục elasticsearch. em copy và đổi tên thư mục này thành "elasticsearch-analysis-vietnamese" rồi paste vào thư mục plugin trong "C:\elasticsearch-5.4.1\plugins" thì vẫn không dùng được.

**Comment by duydo** [comment]
Em bỏ qua bước test nhé: `mvn package -DskipTests`
