### ISSUE TITLE
Can not build custom version elasticsearch

### ISSUE THREAD

**Issue by zonorion** [duydo/elasticsearch-analysis-vietnamese#45]
Hi @duydo!
I cloned your project, then tried to build with this tut http://duydo.me/how-to-build-elasticsearch-vietnamese-analysis-plugin/.
But have two error:

> ERROR   0.00s | VietnameseAnalysisIntegrationTest (suite) <<<
   > Throwable #1: java.lang.RuntimeException: found jar hell in test classpath

> ERROR   0.00s | VietnameseAnalysisTest.initializationError <<<
   > Throwable #1: java.lang.NoClassDefFoundError: org.elasticsearch.test.ESTestCase
Pls tell me how to fix this problems? Thanks

**Comment by duydo** [comment]
@zonorion you can skip tests to build:
```mvn package -DskipTests```
