### ISSUE TITLE
Can't apply elasticsearch-analysis-vietnamese

### ISSUE THREAD

**Issue by phamvannam** [duydo/elasticsearch-analysis-vietnamese#5]
Hello Duy Do
I'm Student.
I researching about elasticsearch search enginer. I try your solution for VietNamese stopwords but i can't using it. It's example.

1. I try with example from elasticsearch.
PUT /index3
{
  "settings": {
    "number_of_shards": 1,
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "type": "standard",
          "stopwords": [
            "bị",
            "và"
          ]
        }
      }
    }
  }
}

then 
GET /index3/_analyze?analyzer=my_analyzer&text="anh bị đi bộ đội và phải nghỉ học"

result:
{

    "tokens": [
        {
            "token": "anh",
            "start_offset": 1,
            "end_offset": 4,
            "type": "<ALPHANUM>",
            "position": 1
        }
        ,
        {
            "token": "đi",
            "start_offset": 8,
            "end_offset": 10,
            "type": "<ALPHANUM>",
            "position": 3
        }
        ,
        {
            "token": "bộ",
            "start_offset": 11,
            "end_offset": 13,
            "type": "<ALPHANUM>",
            "position": 4
        }
        ,
        {
            "token": "đội",
            "start_offset": 14,
            "end_offset": 17,
            "type": "<ALPHANUM>",
            "position": 5
        }
        ,
        {
            "token": "phải",
            "start_offset": 21,
            "end_offset": 25,
            "type": "<ALPHANUM>",
            "position": 7
        }
        ,
        {
            "token": "nghỉ",
            "start_offset": 26,
            "end_offset": 30,
            "type": "<ALPHANUM>",
            "position": 8
        }
        ,
        {
            "token": "học",
            "start_offset": 31,
            "end_offset": 34,
            "type": "<ALPHANUM>",
            "position": 9
        }
    ]

}

is this True.

but i try with your example.
PUT index4
{
  "settings": {
    "number_of_shards": 1,
    "analysis": {
      "analyzer": {
        "my_analyzer": {
          "type": "custom",
          "tokenizer": "vi_tokenizer"
        }
      }
    }
  }
}

and GET /index4/_analyze?analyzer=my_analyzer&text="anh bị đi bộ đội và phải nghỉ học"
result:
{

    "tokens": [
        {
            "token": "anh",
            "start_offset": 1,
            "end_offset": 4,
            "type": "word",
            "position": 2
        }
        ,
        {
            "token": "bị",
            "start_offset": 4,
            "end_offset": 6,
            "type": "word",
            "position": 4
        }
        ,
        {
            "token": "đi",
            "start_offset": 6,
            "end_offset": 8,
            "type": "word",
            "position": 6
        }
        ,
        {
            "token": "bộ đội",
            "start_offset": 8,
            "end_offset": 14,
            "type": "word",
            "position": 8
        }
        ,
        {
            "token": "và",
            "start_offset": 14,
            "end_offset": 16,
            "type": "word",
            "position": 10
        }
        ,
        {
            "token": "phải",
            "start_offset": 16,
            "end_offset": 20,
            "type": "word",
            "position": 12
        }
        ,
        {
            "token": "nghỉ",
            "start_offset": 20,
            "end_offset": 24,
            "type": "word",
            "position": 14
        }
        ,
        {
            "token": "học",
            "start_offset": 24,
            "end_offset": 27,
            "type": "word",
            "position": 16
        }
    ]

}
I don'n understand. this it not work same example stopwords from elasticsearch.
Can you explain for me? 

Thanks very much!

**Comment by duydo** [comment]
I'll check it. Sorry for late reply.

**Comment by duydo** [comment]
@phamvannam your my_analyzer just use the vi_tokenizer, you should add stopwords filter as you did for the index3

**Comment by phamvannam** [comment]
oh...thanks you very much?



2015-09-10 14:22 GMT+07:00 Duy Do <notifications@github.com>:
