### ISSUE TITLE
Công cụ tokenizer cho kết quả sai

### ISSUE THREAD

**Issue by htluandc2** [duydo/elasticsearch-analysis-vietnamese#53]
Hi anh. Em đang dùng thử plug-in của anh.
Elasticsearch: 5.6.5
Plug-in build trên code clone từ master.
Khi em thử nghiệm kết quả như sau:

Input:

> POST _analyze
> {
>   "tokenizer": "vi_tokenizer",
>   "filter": ["lowercase", "stop"], 
>   "text": "công nghệ thông tin Việt Nam"
> }

Output:

> {
>   "tokens": [
>     {
>       "token": "công nghệ thông tin",
>       "start_offset": 0,
>       "end_offset": 19,
>       "type": "phrase",
>       "position": 0
>     },
>     {
>       "token": "việt",
>       "start_offset": 20,
>       "end_offset": 24,
>       "type": "phrase",
>       "position": 1
>     },
>     {
>       "token": "nam",
>       "start_offset": 25,
>       "end_offset": 28,
>       "type": "phrase",
>       "position": 2
>     }
>   ]
> }

**Comment by duydo** [comment]
@htluandc2 Kết quả này do em dùng lowercase filter khiến câu "công nghệ thông tin Việt Nam" bị chuyển thành chữ thường "công nghệ thông tin việt nam" nên bọ tokenizer hoạt động không còn chính xác nữa, các danh từ riêng như Việt Nam phải được giữ nguyên khi đi qua tokenizer.
