### ISSUE TITLE
Cannot install this plugin with elasticsearch 6.5.4

### ISSUE THREAD

**Issue by minhnhat2807** [duydo/elasticsearch-analysis-vietnamese#54]
-> Downloading file:///home/ubuntu/development/elasticsearch-analysis-vietnamese/target/releases/elasticsearch-analysis-vietnamese-6.5.4.zip
[=================================================] 100%?? 
ERROR: This plugin was built with an older plugin structure. Contact the plugin author to remove the intermediate "elasticsearch" directory within the plugin zip.

Could you please re-structure the plugin?

**Comment by minhnhat2807** [comment]
Hi @duydo, could you please tell me whether this repo is still maintenance or not?

Thanks

**Comment by duydo** [comment]
@minhnhat2807 This repo is still maintained but recently I've been busy with other stuff so I cannot spend time on this project.
The current repo is not compatible with ES version 6.x. If you cannot wait for upgrading from me, you can fork and contribute to this plugin.
