### ISSUE TITLE
Compatibility with Elasticsearch 6.4.2

### ISSUE THREAD

**Issue by nvson28** [duydo/elasticsearch-analysis-vietnamese#57]
Hi, 

I have 2 questions regarding the plugins: 

1. I am currently using ES 6.4.2, which version of the plugin should I use? 

2. I have tried to rebuild the plugin from source, but faced with this error:
 ```
[ERROR] Failed to execute goal on project elasticsearch-analysis-vietnamese: Could not resolve dependencies for project org.elasticsearch:elasticsearch-analysis-vietnamese:jar:6.5.3: The following artifacts could not be resolved: vn.hus:nlp-sd:jar:2.0.0, vn.hus:nlp-tokenizer:jar:4.1.1: Could not find artifact vn.hus:nlp-sd:jar:2.0.0 in central (https://repo.maven.apache.org/maven2)
```
Could someone please help? 
Thanks for your time.

**Comment by duydo** [comment]
@nvson28 
> I am currently using ES 6.4.2, which version of the plugin should I use?

All plugins have to follow Elasticsearch version. That mean you have to build the plugin with Elasticsearch 6.4.2

> I have tried to rebuild the plugin from source, but faced with this error

You have to build the vntokenizer first, follow the guide here http://duydo.me/how-to-build-elasticsearch-vietnamese-analysis-plugin/
