### ISSUE TITLE
Build fail with Elasticsearch 6.8.2

### ISSUE THREAD

**Issue by nicksome168** [duydo/elasticsearch-analysis-vietnamese#66]
[INFO] Scanning for projects...
[INFO]
[INFO] --------< org.elasticsearch:elasticsearch-analysis-vietnamese >---------
[INFO] Building elasticsearch-analysis-vietnamese 6.8.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch-analysis-vietnamese ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ elasticsearch-analysis-vietnamese ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/main/java/org/elasticsearch/index/analysis/VietnameseTokenizerFactory.java:[33,9] constructor AbstractTokenizerFactory in class org.elasticsearch.index.analysis.AbstractTokenizerFactory cannot be applied to given types;
  required: org.elasticsearch.index.IndexSettings,java.lang.String,org.elasticsearch.common.settings.Settings
  found: org.elasticsearch.index.IndexSettings,org.elasticsearch.common.settings.Settings
  reason: actual and formal argument lists differ in length
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.759 s
[INFO] Finished at: 2019-09-04T14:45:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch-analysis-vietnamese: Compilation failure
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/main/java/org/elasticsearch/index/analysis/VietnameseTokenizerFactory.java:[33,9] constructor AbstractTokenizerFactory in class org.elasticsearch.index.analysis.AbstractTokenizerFactory cannot be applied to given types;
[ERROR]   required: org.elasticsearch.index.IndexSettings,java.lang.String,org.elasticsearch.common.settings.Settings
[ERROR]   found: org.elasticsearch.index.IndexSettings,org.elasticsearch.common.settings.Settings
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by nicksome168** [comment]
I checked the previous [commits](
https://github.com/duydo/elasticsearch-analysis-vietnamese/commit/5bbc810f0a28d8927b42e86626b184982d115f5e)
 and found this. 

>  public VietnameseTokenizerFactory(IndexSettings indexSettings, Environment environment, String name, Settings settings) {
        super(indexSettings, settings);	        super(indexSettings, name, settings);

However, after I added _name_ variable to the function _super_, another issue was raised. 

> [INFO] Scanning for projects...
[INFO]
[INFO] --------< org.elasticsearch:elasticsearch-analysis-vietnamese >---------
[INFO] Building elasticsearch-analysis-vietnamese 6.8.2
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ elasticsearch-analysis-vietnamese ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ elasticsearch-analysis-vietnamese ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ elasticsearch-analysis-vietnamese ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ elasticsearch-analysis-vietnamese ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/test/java/org/elasticsearch/index/analysis/VietnameseAnalysisIntegrationTest.java:[48,22] cannot find symbol
  symbol:   class Response
  location: class org.elasticsearch.action.admin.indices.analyze.AnalyzeAction
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/test/java/org/elasticsearch/index/analysis/VietnameseAnalysisIntegrationTest.java:[78,53] long cannot be dereferenced
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.689 s
[INFO] Finished at: 2019-09-04T14:58:45+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:testCompile (default-testCompile) on project elasticsearch-analysis-vietnamese: Compilation failure: Compilation failure:
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/test/java/org/elasticsearch/index/analysis/VietnameseAnalysisIntegrationTest.java:[48,22] cannot find symbol
[ERROR]   symbol:   class Response
[ERROR]   location: class org.elasticsearch.action.admin.indices.analyze.AnalyzeAction
[ERROR] /Users/myMac/Downloads/vn-nlp-libraries/nlp-parent/elasticsearch-analysis-vietnamese/src/test/java/org/elasticsearch/index/analysis/VietnameseAnalysisIntegrationTest.java:[78,53] long cannot be dereferenced
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
FAIL

**Comment by duydo** [comment]
@nicksome168 Some Elasticsearch v7 APIs are not compatible with v6.x. To build the plugin for v6, check out this branch https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/feature/v6.8.2

**Comment by nicksome168** [comment]
@duydo I've built and tested. It works well. Thank you :)
