### ISSUE TITLE
Build fail for ES 7.4.1

### ISSUE THREAD

**Issue by hoangnd17899** [duydo/elasticsearch-analysis-vietnamese#69]
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.006 s
[INFO] Finished at: 2019-10-30T11:32:38+07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project elasticsearch-analysis-vietnamese: Compilation failure
[ERROR] /E:/MISA/elasticsearch-analysis-vietnamese/src/main/java/org/elasticsearch/index/analysis/VietnameseTokenizerFactory.java:[33,9] constructor AbstractTokenizerFactory in class org.elasticsearch.index.analysis.AbstractTokenizerFactory cannot be applied to given types;
[ERROR]   required: org.elasticsearch.index.IndexSettings,org.elasticsearch.common.settings.Settings,java.lang.String
[ERROR]   found: org.elasticsearch.index.IndexSettings,org.elasticsearch.common.settings.Settings
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by bogiahuy** [comment]
Mình cũng bị giống thế này. Bạn build được chưa nhỉ

**Comment by dumln86** [comment]
I have been got same error with elasticsearch 7.5.1. Could you please help fix it. Thank you so much
