### ISSUE TITLE
How about with ES 6.x?

### ISSUE THREAD

**Issue by cuongntr** [duydo/elasticsearch-analysis-vietnamese#79]
Chào Duy Dỗ, 
Thật vui khi tìm thấy repo này của bạn, nhưng cũng thật buồn là mình lại dùng ES6.
Cho mình xin phép hỏi là tại sao vậy.

Thông cảm cho mình vì tiếng Anh của mình không có nhiều vốn từ!

**Comment by TsunamiNori** [comment]
ES6 phải tự build thì phải. Có branch cho bản 6.8.2
> https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/feature/v6.8.2

**Comment by tyrantkhan** [comment]
could we get an official release of the binary in the releases tab?
