### ISSUE TITLE
Settings sample for filter stopwords

### ISSUE THREAD

**Issue by buithehien1991** [duydo/elasticsearch-analysis-vietnamese#8]
I've just written settings but I'm not sure about that. 
```
analysis: {
               analyzer: {
                   email: {
                       tokenizer: 'keyword',
                       filter: ['lowercase']
                   },
                   vietnamese: {
                       tokenizer: 'vi_analyzer',
                       filter: ['lowercase', 'vi_stop']
                   }
               }
           } 
```
Could you correct me with I was wrong?

**Comment by buithehien1991** [comment]
I've seen on https://github.com/duydo/elasticsearch-analysis-vietnamese/blob/master/src/main/java/org/apache/lucene/analysis/vi/VietnameseAnalyzer.java
```java
final List<String> stopWords = Arrays.asList(
                "bị", "bởi", "cả", "các", "cái", "cần", "càng", "chỉ", "chiếc", "cho", "chứ", "chưa", "chuyện",
                "có", "có thể", "cứ", "của", "cùng", "cũng", "đã", "đang", "đây", "để", "đến nỗi", "đều", "điều",
                "do", "đó", "được", "dưới", "gì", "khi", "không", "là", "lại", "lên", "lúc", "mà", "mỗi", "một cách",
                "này", "nên", "nếu", "ngay", "nhiều", "như", "nhưng", "những", "nơi", "nữa", "phải", "qua", "ra",
                "rằng", "rằng", "rất", "rất", "rồi", "sau", "sẽ", "so", "sự", "tại", "theo", "thì", "trên", "trước",
                "từ", "từng", "và", "vẫn", "vào", "vậy", "vì", "việc", "với", "vừa"
        );
```

So, how to use it? on setting of filter. 
Thank you so much....

**Comment by buithehien1991** [comment]
Addition, I'm working on Rails project and use Chewy gem using elasticsearch as wrapper, So I think setting of it like as setting for elasticsearch.
You can see here: https://github.com/toptal/chewy

Thank you so much for your help.

**Comment by buithehien1991** [comment]
The first time, I run like:
http://localhost:9200/_analyze?analyzer=vi_analyzer&text="anh bị đi bộ đội và phải nghỉ học"

But have error: {"error":"ElasticsearchIllegalArgumentException[failed to find analyzer [vi_analyzer]]","status":400}

I installed successfully your plugin and run server from bin/elasticsearch.
Could you please show me reason of this cause.
Thank you soi much for your help.

**Comment by duydo** [comment]
@buithehien1991 You don't need to define a custom Vietnamese analyzer, you can use vi_analyzer directly in mapping:

```...
"properties: {
    "text": { "type": "string", "analyzer": "vi_analyzer"}
}
```

In case you want to define a custom Vietnamese analyzer to apply other filters, you can use vi_tonkenizer:

```
"analysis": {
    "analyzer": {
        "custom_vi": {
              "tokenizer": "vi_tokenizer",
              "filter": ["lowercase", "stop",...]
        } 
    }
}
```

**Comment by duydo** [comment]
Closed due to lack of feedback.
