### ISSUE TITLE
Error when build plugin from source

### ISSUE THREAD

**Issue by duccanh0022** [duydo/elasticsearch-analysis-vietnamese#9]
Hi,
the first thanks to the nice plugin.
I have a problem. i build plugin from your source, when i run elasticsearch have an error:

{
  "error": "NoClassDefFoundError[vn/hus/nlp/sd/SentenceDetectorFactory]; nested: ClassNotFoundException[vn.hus.nlp.sd.SentenceDetectorFactory]; ",
  "status": 500
}

This is my source
<img width="327" alt="screen shot 2015-10-21 at 11 36 54 pm" src="https://cloud.githubusercontent.com/assets/4942484/10643379/b2fd1c6e-784c-11e5-91c8-c8e72a4fd37d.png">

Plz help me,
Thanks you!

**Comment by duydo** [comment]
You are missing vn tokenizer jars in the class path, make sure that all jar files in libs folder are in the class path.

**Comment by duydo** [comment]
Closed due to lack of feedback
