### ISSUE TITLE
Plugin for ES 7.10?

### ISSUE THREAD

**Issue by huynhminhphuc** [duydo/elasticsearch-analysis-vietnamese#93]
Dear Duy Do, 

Now I'm getting trouble for build ES-analysis-vietnamese plugin myself for ES 7.10.1. 
I follow your instructions in [https://duydo.me/how-to-build-elasticsearch-vietnamese-analysis-plugin/](url) but i received an error as below:

> package javax.xml.bind.annotation does not exist

I've install JDK 10 but I got a new error:

> [ERROR] /D:/BuilPlugin/elasticsearch-analysis-vietnamese/src/test/java/org/elasticsearch/index/analysis/VietnameseAnalysisTest.java:[10,42] cannot find symbol
> [ERROR]   symbol:   class IndexMetaData
> [ERROR]   location: package org.elasticsearch.cluster.metadata

Please help me

**Comment by anhtuanluu** [comment]
I have the same error

**Comment by viiiprock** [comment]
Cái này mình cũng đang bị, lỗi này từ java chứ ko liên quan đến ES version
`java.xml.bind (JAXB) - REMOVED`

Java 8 - OK
Java 9 - DEPRECATED
Java 10 - DEPRECATED
Java 11 - REMOVED

Phải dùng bản 8

**Comment by tl-minhtang** [comment]
![image](https://user-images.githubusercontent.com/78368153/114902498-1574be00-9e40-11eb-82dc-684f361376a5.png)
I have the same error

**Comment by iceteahh** [comment]
Same Error why r u close it?

**Comment by jpena88** [comment]
Getting the same error, but I guess there is no fix 🤷
