### ISSUE TITLE
Plugin Support for OpenSearch

### ISSUE THREAD

**Issue by soosinha** [duydo/elasticsearch-analysis-vietnamese#95]
AWS has released OpenSearch with ALv2 license: https://github.com/opensearch-project/OpenSearch
Is there any plan to support this analyzer for OpenSearch ?

**Comment by duydo** [comment]
@soosinha To support OpenSearch, we just build and test the plugin for Elasticsearch 7.10.2 is enough, isn't it?

**Comment by duydo** [comment]
@soosinha I've created the repo https://github.com/duydo/opensearch-analysis-vietnamese for supporting OpenSearch, but maven cannot find  dependencies, can you please look at it?

**Comment by soosinha** [comment]
@duydo Thanks for taking the OpenSearch changes. Currently AWS team is working publishing OpenSearch to public maven repos. So maven is not able to find OpenSearch dependency. We need to build and publishly OpenSearch locally to resolve this. This process is mentioned here: https://github.com/opensearch-project/opensearch-plugins

I have created a pull request to update the documentation: https://github.com/duydo/opensearch-analysis-vietnamese/pull/1
There are still some compilation failures after resolving the OpenSearch dependency issue. Can you look into those ?

**Comment by duydo** [comment]
@soosinha Sure, I'll look at it.
Btw, I'll close this ticket. Any issues relates to OpenSearch should be opened on opensearch-analysis-vietnamese repo.

**Comment by duydo** [comment]
@soosinha I've just fixed the compilation failures and updated the repo, now it is able to compile.
