### ISSUE TITLE
The plugin with new C++ tokenizer

### ISSUE THREAD

**Issue by duydo** [duydo/elasticsearch-analysis-vietnamese#96]
From version 7.12.11, I use [Cốc Cốc C++ tokenizer](https://github.com/coccoc/coccoc-tokenizer) for the plugin instead of VnTokenizer.  So I close all issues relates to VnTokenizer, I won't maintain the plugin with the VnTokenizer anymore.

The Cốc Cốc tokenizer is used in Cốc Cốc Search and Ads systems and the main goal in its development was to reach high performance while keeping the quality reasonable for search ranking needs.

If you want to use the plugin with prior versions of Elasticsearch, you can build the plugin yourself with the guide in README file.

**Comment by soosinha** [comment]
@duydo The packaged zip of the plugin does not contain the tokenizer. What is the process for installing the new tokenizer on an Elasticsearch node ?

**Comment by duydo** [comment]
@soosinha The tokenizer is written in C++ so we have to build it as a shared lib on Elasticsearch node. You can refer the installation guide in README file (Step 1).

**Comment by kennynguyeenx** [comment]
@duydo I tried to build and run your plugin with [Cốc Cốc C++ tokenizer](https://github.com/coccoc/coccoc-tokenizer) and got crash time to time
Message in log
`double free or corruption (fasttop)`
ES version: >= 7.12.1
Could you help to check when you have time, pls?
I think we have problem with new tokenizer or binding from C++ to Java
Thank you

**Comment by linuxpham** [comment]
Try with : https://github.com/miczone/coccoc-tokenizer

**Comment by duydo** [comment]
@kennynguyeenx 
> =============== Updated: I checked and found that we get this problem only when create index with more than 1 shards. ES uses 1 thread for each shard and I think this C++ library is not thread safe so it causes crash

This issue has been fixed in this branch https://github.com/duydo/elasticsearch-analysis-vietnamese/tree/feature/search-issues

**Comment by ManWithASideQuest** [comment]
Hi, @duydo 
We're using the coccoc-tokenizer and we keep on getting this error:
12]: *** Error in `/usr/share/elasticsearch/jdk/bin/java': double free or corruption (!prev): 0x00007f49dc04bf70 ***
12]: ======= Backtrace: =========
12]: /lib64/libc.so.6(+0x81329)[0x7f4a8754a329]
12]: /usr/lib/libcoccoc_tokenizer_jni.so(_ZN3spp11sparsetableISt4pairIKifENS_14libc_allocatorIS3_EEE12_free_groupsEv+0x2d)[0x7f49c92e7fed]

ES version is 7.16.2

Thanks!
