### ISSUE TITLE
[Docker fail install plugin] no coccoc_tokenizer_jni in java.library.path

### ISSUE THREAD

**Issue by viiiprock** [duydo/elasticsearch-analysis-vietnamese#97]
Error occur when using with docker
Step to reproduce:
1/ Build Plugin following steps as document
2/ Run `docker-compose up -d` with the docker-compose.yml provided in the repository
3/ Logs container

```
fatal error in thread [elasticsearch[89d35512fcee][masterService#updateTask][T#1]], exiting
java.lang.UnsatisfiedLinkError: no coccoc_tokenizer_jni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2447)
```

**Comment by duydo** [comment]
@viiiprock To get the plugin work with Docker, we need to build the C++ tokenizer in Docker images as shared library. @taivc-teko is the author of the docker integration, I don't know if he can fix this issue.

**Comment by viiiprock** [comment]
@duydo aha, I got the idea, so I have to copy whole `build` directory to container volume. In terms of the directory of plugin is `/usr/share/elasticsearch/plugin/elasticsearch-analysis-vietnamese-${ES_VERSION}.zip` , where should I copy the tokenizer build folder to get it share? `/usr/java/packages/lib` or `/usr/java/packages/lib` or `/usr/lib`?

**Comment by phat-go2joy** [comment]
hi @viiiprock , em cũng đang gặp lỗi giống a khi sử dụng Docker. Ko biết anh đã giải quyết đc chưa a ?

**Comment by phat-go2joy** [comment]
anh @duydo oi, anh có thể share tài liệu về cách build C++ tokenizer in Docker images as shared library ko ạ. Em bữa giờ cũng gặp lỗi "no coccoc_tokenizer_jni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"," khi run plugin với container. Hy vọng anh xem giúp ạ

**Comment by viiiprock** [comment]
@phat-go2joy Hi, mình chưa quay lại với task này, hiện tại vẫn đang dùng tạm cách ghép keywords với nhau dùng asciifolding thôi. 
Tuy nhiên mình nghĩ là vấn đề sẽ được giải quyết ở đây, chỉ cần path đúng  là được 
https://www.facebook.com/groups/elasticsearchvn/permalink/2264795696988534/?comment_id=2264877240313713&reply_comment_id=2264879540313483&notif_id=1622295100313591&notif_t=group_comment&ref=notif

**Comment by dinhan92** [comment]
@viiiprock Hi bạn, mình cũng mắc lỗi này khi chạy elasticsearch, bạn sửa thế nào vậy? Mình ko vào được link facebook trên @@

**Comment by dvdieu** [comment]
> anh @duydo oi, anh có thể share tài liệu về cách build C++ tokenizer in Docker images as shared library ko ạ. Em bữa giờ cũng gặp lỗi "no coccoc_tokenizer_jni in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib"," khi run plugin với container. Hy vọng anh xem giúp ạ

Bạn cài C++ tokenizer trên máy host, sau đó mount vào docker hoặc là build lại images copy vào hoặc là build ở trong docker

**Comment by viiiprock** [comment]
Xin lỗi các bạn @phat-go2joy @dinhan92 , mình bận quá, giờ mới quay lại với cái này, hiện tại mình đang dùng với 7.14.2, 
Không biết các bạn còn cần không, mình có tạo demo tại đây.
https://github.com/viiiprock/es-vietnamese-docker
Do mình lười viết dài dòng nên có làm 1 clip ngắn để hướng dẫn https://www.youtube.com/watch?v=aAuW_wV81Xk
